<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="agi-lt-882" name="Scenario_Component.LaunchUrl" tests="6" failures="0" timestamp="04 Feb 2021 02:10:16 GMT" time="122.127" errors="1">
  <testcase name="testLaunchUrl" time="0.150" classname="Scenario_Component.LaunchUrl"/>
  <testcase name="testLoginLogout" time="38.871" classname="Scenario_Component.LaunchUrl"/>
  <testcase name="testAerRegistration" time="14.679" classname="Scenario_Component.LaunchUrl"/>
  <testcase name="testCaseIntake" time="7.377" classname="Scenario_Component.LaunchUrl"/>
  <testcase name="testFullDataEntry" time="44.485" classname="Scenario_Component.LaunchUrl"/>
  <testcase name="testAERRegistrationInformation" time="16.565" classname="Scenario_Component.LaunchUrl">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Generic_Component.ExcelReadWrite.writecell(ExcelReadWrite.java:95)
at PageObject_Component.AERRegistrationinformation.getCaseNumber(AERRegistrationinformation.java:56)
at Scenario_Component.LaunchUrl.testAERRegistrationInformation(LaunchUrl.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testAERRegistrationInformation -->
</testsuite> <!-- Scenario_Component.LaunchUrl -->
